apiVersion: webapp.test.vmware/v1
kind: Guestbook
metadata:
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/instance: guestbook-sample
    app.kubernetes.io/part-of: kop
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kop
  name: guestbook-sample
spec:
  # TODO(user): Add fields here
